(self.AMP=self.AMP||[]).push({n:"amp-video",v:"1521658019509",f:(function(AMP){var h;(function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a})(this);function aa(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function m(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ba=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function q(a){var b=Object.create(null);if(!a)return b;for(var c;c=ba.exec(a);){var d=m(c[1],c[1]),e=c[2]?m(c[2],c[2]):"";b[d]=e}return b};var r="";function ca(a){var b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;var d=q(c.location.originalHash||c.location.hash),e=q(c.location.search);r||(r=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011521658019509");c=b.AMP_MODE={localDev:!1,development:!("1"!=d.development&&!c.AMP_DEV_MODE),examiner:"2"==d.development,filter:d.filter,minified:!0,lite:void 0!=e.amp_lite,test:!1,log:d.log,version:"1521658019509",rtvVersion:r}}return c};var da=Object.prototype.toString;function t(a){if(!a)return[];for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return b}function u(a){return"number"===typeof a&&isFinite(a)};self.log=self.log||{user:null,dev:null,userForEmbed:null};var v=self.log;function w(){if(!v.user)throw Error("failed to call initLogConstructor");return v.user}function x(){if(v.dev)return v.dev;throw Error("failed to call initLogConstructor");};function ea(a){var b=Object.create(null);a&&Object.assign(b,a);return b};function fa(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var y=self.AMP_CONFIG||{},ga=("string"==typeof y.cdnProxyRegex?new RegExp(y.cdnProxyRegex):y.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;var z,A,ha=["javascript:","data:","vbscript:"];
function B(a){var b;z||(z=self.document.createElement("a"),A=self.UrlCache||(self.UrlCache=Object.create(null)));var c=A[a];if(c)return c;var d=z;d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=d.origin&&
"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;var g=e,f=g;return b?f:A[a]=f}function ia(a){"string"==typeof a&&(a=B(a));var b;(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function C(a,b){var c;c=void 0===c?"source":c;w().assert(null!=a,"%s %s must be available",b,c);var d=a;w().assert(ia(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)}function ja(a){if(!a)return!0;"string"==typeof a&&(a=B(a));return!ha.includes(a.protocol)};function ka(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;if(b=b!=(b.__AMP_TOP||b)&&la(b,"action")?D(b,"action"):null)return b}return E(a,"action")}function ma(a,b,c){var d=na(a),e=oa(d);a=e;var g=pa(a),f=g[b];f||(f=g[b]={obj:null,promise:null,resolve:null,context:null,ctor:null});f.ctor||f.obj||(f.ctor=c,f.context=d,f.resolve&&D(a,b))}function F(a,b){a=a.__AMP_TOP||a;return D(a,b)}function E(a,b){a=na(a);a=oa(a);return D(a,b)}
function na(a){return a.nodeType?F((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function oa(a){a=na(a);return a.isSingleDoc()?a.win:a}function D(a,b){la(a,b);var c=pa(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function pa(a){var b=a.services;b||(b=a.services={});return b}function la(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function qa(a){a.parentElement&&a.parentElement.removeChild(a)}function ra(a,b){for(var c,d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null}function sa(a){var b="amp-story";if(a.closest)return a.closest(b);b=b.toUpperCase();return ra(a,function(a){return a.tagName==b})}var G;function ta(a){a=a.ownerDocument;try{var b=a.createElement("div"),c=a.createElement("div");b.appendChild(c);return b.querySelector(":scope div")===c}catch(d){return!1}}
function H(a,b){null==G&&(G=ta(a));if(G)return a.querySelectorAll(":scope "+b);a.classList.add("i-amphtml-scoped");b=a.querySelectorAll(".i-amphtml-scoped "+b);a.classList.remove("i-amphtml-scoped");return b}function ua(a){var b=a.body.getAttribute("dir")||a.documentElement.getAttribute("dir")||"ltr";return"rtl"==b};function I(a){return E(a,"viewport")};function va(a){a:{var b;try{b=a.document.cookie}catch(k){b=""}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),d=c.indexOf("="),e;if(e=-1!=d)e=c.substring(0,d).trim(),e="AMP_EXP"==m(e,void 0);if(e){a=c.substring(d+1).trim();a=m(a,a);break a}}a=null}var g=a,f=g?g.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<f.length;b++)0!=f[b].length&&("-"==f[b][0]?a[f[b].substr(1)]=!1:a[f[b]]=!0);return a};var J,wa="Webkit webkit Moz moz ms O o".split(" ");function xa(a,b){var c=void 0;if(fa(b,"--"))return b;J||(J=ea());var d=J[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var g=0;g<wa.length;g++){var f=wa[g]+e;if(void 0!==a[f]){e=f;break a}}e=""}var k=e;void 0!==a[k]&&(d=k)}c||(J[b]=d)}return d}function ya(a,b,c){var d;(b=xa(a.style,b))&&(a.style[b]=d?c+d:c)}function K(a,b){for(var c in b)ya(a,c,b[c])}
function za(a,b){"number"==typeof a&&(a+="px");if(void 0===b)return"translate("+a+")";"number"==typeof b&&(b+="px");return"translate("+a+", "+b+")"};var L;function Aa(a,b,c){function d(a){try{return f(a)}catch(p){throw self.reportError(p),p;}}var e=void 0,g=a,f=c,k=Ba(),l=!1;e&&(l=e.capture);g.addEventListener(b,d,k?e:l);return function(){g&&g.removeEventListener(b,d,k?e:l);d=g=f=null}}function Ba(){if(void 0!==L)return L;L=!1;try{var a={get capture(){L=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return L};function M(a,b,c){return Aa(a,b,c)}function Ca(a,b){var c=b,d=Aa(a,"load",function(a){try{c(a)}finally{c=null,d()}});return d}function Da(a){var b,c,d=new Promise(function(b){c=Ca(a,b)});d.then(c,c);b&&b(c);return d};function Ea(){this.H=null}h=Ea.prototype;h.add=function(a){var b=this;this.H||(this.H=[]);this.H.push(a);return function(){b.remove(a)}};h.remove=function(a){this.H&&(a=this.H.indexOf(a),-1<a&&this.H.splice(a,1))};h.removeAll=function(){this.H&&(this.H.length=0)};h.fire=function(a){if(this.H)for(var b=this.H,c=0;c<b.length;c++)(0,b[c])(a)};h.getHandlerCount=function(){return this.H?this.H.length:0};function Fa(a,b,c,d){return{left:a,top:b,width:c,height:d,bottom:b+d,right:a+c,x:a,y:b}}function Ga(a,b){return a&&b?a.left==b.left&&a.top==b.top&&a.width==b.width&&a.height==b.height:!1};function Ha(a,b){function c(){d=0;var f=500-(a.Date.now()-e);if(0<f)d=a.setTimeout(c,f);else{var k=g;g=null;b.apply(null,k)}}var d=0,e=0,g=null;return function(b){for(var f=[],l=0;l<arguments.length;++l)f[l-0]=arguments[l];e=a.Date.now();g=f;d||(d=a.setTimeout(c,500))}};function Ia(a,b,c,d,e){var g=c,f=b;b>c&&(g=b,f=c);a<f?a=f:a>g&&(a=g);return(a-b)*(e-d)/(c-b)+d};function N(a,b,c,d){var e=new Ja(0,0,a,b,c,d,1,1);return e.solveYValueFromXValue.bind(e)}function Ja(a,b,c,d,e,g,f,k){this.x0=a;this.y0=b;this.x1=c;this.y1=d;this.x2=e;this.y2=g;this.x3=f;this.y3=k}h=Ja.prototype;h.solveYValueFromXValue=function(a){return this.getPointY(this.solvePositionFromXValue(a))};
h.solvePositionFromXValue=function(a){var b=1E-6,c=(a-this.x0)/(this.x3-this.x0);if(0>=c)return 0;if(1<=c)return 1;for(var d=0,e=1,g=0,f=0;8>f;f++){var g=this.getPointX(c),k=(this.getPointX(c+b)-g)/b;if(Math.abs(g-a)<b)return c;if(Math.abs(k)<b)break;else g<a?d=c:e=c,c-=(g-a)/k}for(f=0;Math.abs(g-a)>b&&8>f;f++)g<a?(d=c,c=(c+e)/2):(e=c,c=(c+d)/2),g=this.getPointX(c);return c};
h.getPointX=function(a){if(0==a)return this.x0;if(1==a)return this.x3;var b=this.lerp(this.x0,this.x1,a),c=this.lerp(this.x1,this.x2,a),d=this.lerp(this.x2,this.x3,a),b=this.lerp(b,c,a),c=this.lerp(c,d,a);return this.lerp(b,c,a)};h.getPointY=function(a){if(0==a)return this.y0;if(1==a)return this.y3;var b=this.lerp(this.y0,this.y1,a),c=this.lerp(this.y1,this.y2,a),d=this.lerp(this.y2,this.y3,a),b=this.lerp(b,c,a),c=this.lerp(c,d,a);return this.lerp(b,c,a)};h.lerp=function(a,b,c){return a+c*(b-a)};
var Ka=N(.25,.1,.25,1),La=N(.42,0,1,1),Ma=N(0,0,.58,1),Na=N(.42,0,.58,1),Oa={linear:function(a){return a},ease:Ka,"ease-in":La,"ease-out":Ma,"ease-in-out":Na};function Pa(a){if(!a)return null;if("string"==typeof a){if(-1!=a.indexOf("cubic-bezier")){var b=a.match(/cubic-bezier\((.+)\)/);if(b&&(b=b[1].split(",").map(parseFloat),4==b.length)){for(var c=0;4>c;c++)if(isNaN(b[c]))return null;return N(b[0],b[1],b[2],b[3])}return null}return Oa[a]}return a};function Qa(){}function O(a,b){this.S=a;this.m=b||F(self,"vsync");this.pa=null;this.F=[]}function Ra(a,b){var c;return(new O(a)).setCurve(c).add(0,b,1).start(200)}O.prototype.setCurve=function(a){a&&(this.pa=Pa(a));return this};O.prototype.add=function(a,b,c,d){this.F.push({delay:a,func:b,duration:c,curve:Pa(d)});return this};
O.prototype.start=function(a){var b=new P(this.m,this.S,this.F,this.pa,a);a=b;a.ya=Date.now();a.aa=!0;a.m.canAnimate(a.S)?a.Aa(a.za):(x().warn("Animation","cannot animate"),Q(a,!1,0));return b};
function P(a,b,c,d,e){var g=this;this.m=a;this.S=b;this.F=[];for(b=0;b<c.length;b++){var f=c[b];this.F.push({delay:f.delay,func:f.func,duration:f.duration,curve:f.curve||d,started:!1,completed:!1})}this.Ga=e;this.Na=this.Ma=this.ya=0;this.aa=!1;this.za={};this.va=new Promise(function(a,b){g.Ia=a;g.Ha=b});this.Aa=this.m.createAnimTask(this.S,{mutate:this.Ja.bind(this)})}P.prototype.then=function(a,b){return a||b?this.va.then(a,b):this.va};
P.prototype.thenAlways=function(a){a=a||Qa;return this.then(a,a)};P.prototype.halt=function(a){Q(this,!1,a||0)};function Q(a,b,c){if(a.aa){a.aa=!1;if(0!=c){1<a.F.length&&a.F.sort(function(a,b){return a.delay+a.duration-(b.delay+b.duration)});try{if(0<c)for(c=0;c<a.F.length;c++)a.F[c].func(1,!0);else for(var d=a.F.length-1;0<=d;d--)a.F[d].func(0,!1)}catch(e){x().error("Animation","completion failed: "+e,e),b=!1}}b?a.Ia():a.Ha()}}
P.prototype.Ja=function(){if(this.aa){for(var a=Date.now(),b=Math.min((a-this.ya)/this.Ga,1),c=0;c<this.F.length;c++){var d=this.F[c];!d.started&&b>=d.delay&&(d.started=!0)}for(c=0;c<this.F.length;c++)if(d=this.F[c],d.started&&!d.completed)a:{var e,g;if(0<d.duration){if(e=g=Math.min((b-d.delay)/d.duration,1),d.curve&&1!=e)try{e=d.curve(g)}catch(f){x().error("Animation","step curve failed: "+f,f);Q(this,!1,0);break a}}else e=g=1;1==g&&(d.completed=!0);try{d.func(e,d.completed)}catch(f){x().error("Animation",
"step mutate failed: "+f,f),Q(this,!1,0)}}1==b?Q(this,!0,0):this.m.canAnimate(this.S)?this.Aa(this.za):(x().warn("Animation","cancel animation"),Q(this,!1,0))}};function Sa(a){var b;b=void 0===b?" ":b;return function(c,d){for(var e=[],g=0;g<a.length;g++){var f=(0,a[g])(c,d);"string"==typeof f&&e.push(f)}return e.join(b)}}function Ta(a,b){return function(c,d){for(var e in b)ya(a,e,b[e](c,d))}}function Ua(a,b){return function(c){return a+(b-a)*c}}function Va(a){return function(b){return a(b)+"px"}}
function Wa(a,b){return function(c){var d=a(c);"number"==typeof d&&(d+="px");if(!b)return"translate("+d+")";c=b(c);"number"==typeof c&&(c+="px");return"translate("+d+","+c+")"}}function Xa(){var a=Ua(.6,.6);return function(b){return"scale("+a(b)+")"}};var Ya={title:"",artist:"",album:"",artwork:[{src:""}]};function Za(a,b,c,d){var e=a.navigator;"mediaSession"in e&&a.MediaMetadata&&(e.mediaSession.metadata=new a.MediaMetadata(Ya),$a(b),e.mediaSession.metadata=new a.MediaMetadata(b),e.mediaSession.setActionHandler("play",c),e.mediaSession.setActionHandler("pause",d))}
function ab(a){var b=a.querySelector('script[type="application/ld+json"]');if(b){var c;a:{try{c=JSON.parse(b.textContent);break a}catch(e){}c=void 0}var d=c;if(d&&d.image){if("string"===typeof d.image)return d.image;if(d.image["@list"]&&"string"===typeof d.image["@list"][0])return d.image["@list"][0];if("string"===typeof d.image.url)return d.image.url;if("string"===typeof d.image[0])return d.image[0]}}}
function $a(a){a&&a.artwork&&(Array.isArray(a.artwork),a.artwork.forEach(function(a){if(a){var b="[object Object]"===da.call(a)?a.src:a;w().assert(ja(b))}}))};function R(){this.Y=!1;this.qa=new Ea}R.prototype.onSessionEnd=function(a){this.qa.add(a)};R.prototype.beginSession=function(){this.Y=!0};R.prototype.endSession=function(){this.Y&&this.qa.fire();this.Y=!1};R.prototype.isSessionActive=function(){return this.Y};function bb(a,b,c,d){this.element=b;this.ra=d;this.fidelity=c;this.turn=0==c?Math.floor(4*Math.random()):0;this.$=null;this.l=I(a)}
bb.prototype.update=function(a){var b=this;if(!a){if(0!=this.turn){this.turn--;return}0==this.fidelity&&(this.turn=4)}var c=this.l.getSize(),d=Fa(0,0,c.width,c.height);this.l.getClientRectAsync(this.element).then(function(a){var c={positionRect:a,viewportRect:d,relativePos:""},e=b.$;if(!(e&&Ga(e.positionRect,c.positionRect)&&Ga(e.viewportRect,c.viewportRect))){var e=c.positionRect,k=c.viewportRect;c.relativePos=e.top<k.top?"top":e.bottom>k.bottom?"bottom":"inside";k=c.viewportRect;e.top<=k.bottom&&
k.top<=e.bottom&&e.left<=k.right&&k.left<=e.right?(b.$=c,b.ra(c)):b.$&&(b.$=null,c.positionRect=null,b.ra(c))}})};function S(a){var b=this;this.o=a;this.Ca=a.win;this.N=[];this.m=F(this.Ca,"vsync");this.l=I(a);this.L=[];this.ea=this.la=this.ia=!1;this.Fa=Ha(this.Ca,function(){b.ia=!1})}S.prototype.observe=function(a,b,c){var d=new bb(this.o,a,b,c);this.N.push(d);this.ea||cb(this);d.update()};S.prototype.unobserve=function(a){for(var b=0;b<this.N.length;b++)if(this.N[b].element==a){this.N.splice(b,1);if(0==this.N.length)for(this.ea=!1;this.L.length;)this.L.pop()();return}x().error("POSITION_OBSERVER","cannot unobserve unobserved element")};
function cb(a){a.ea=!0;a.L.push(a.l.onScroll(function(){a.Fa();a.ia=!0;a.la||db(a)}));a.L.push(a.l.onResize(function(){a.updateAllEntries(!0)}))}S.prototype.updateAllEntries=function(a){for(var b=0;b<this.N.length;b++)this.N[b].update(a)};function db(a){a.updateAllEntries();a.la=!0;a.ia?a.m.measure(function(){db(a)}):a.la=!1}function eb(a){ma(a,"position-observer",function(){return new S(a)})};function fb(a){var b=this;this.ampdoc=a;this.l=I(this.ampdoc);this.A=null;this.wa=this.xa=!1;this.X=this.na=null;this.Ba=F(a.win,"timer");this.Da=ka(a);this.oa=function(){for(var a=0;a<b.A.length;a++){var d=b.A[a];if("paused"!==d.getPlayingState()){T(d,"video-seconds-played");var e,g=d.video.getCurrentTime(),f=d.video.getDuration();u(g)&&u(f)&&0<f&&(e=b.ampdoc.win,g={time:g,percent:g/f},f={detail:g},Object.assign(f,void 0),"function"==typeof e.CustomEvent?e=new e.CustomEvent("video-manager.timeUpdate",
f):(e=e.document.createEvent("CustomEvent"),e.initCustomEvent("video-manager.timeUpdate",!!f.bubbles,!!f.cancelable,g)),b.Da.trigger(d.video.element,"timeUpdate",e,1))}}b.Ba.delay(b.oa,1E3)};this.Ba.delay(this.oa,1E3)}h=fb.prototype;
h.register=function(a,b){b=void 0===b?!0:b;var c=a;c.registerAction("play",c.play.bind(c,!1),1);c.registerAction("pause",c.pause.bind(c),1);c.registerAction("mute",c.mute.bind(c),1);c.registerAction("unmute",c.unmute.bind(c),1);c.registerAction("fullscreen",c.fullscreenEnter.bind(c),1);a.supportsPlatform()&&(this.A=this.A||[],c=new gb(this,a,b),hb(this,c),ib(this,c),jb(this,c),this.A.push(c),a.element.dispatchCustomEvent("registered"),a.element.classList.add("i-amphtml-video-interface"))};
function hb(a,b){M(b.video.element,"amp:video:visibility",function(a){var c=a.data;c&&1==c.visible?b.updateVisibility(!0):b.updateVisibility()});M(b.video.element,"reloaded",function(){b.videoLoaded()});if(!a.xa){var c=function(){for(var b=0;b<a.A.length;b++)a.A[b].updateVisibility()};a.l.onScroll(c);a.l.onChanged(c);a.xa=!0}}
function jb(a,b){if(b.hasFullscreenOnLandscape){var c=a.ampdoc.win,d=c.screen,e=function(){var a,e=a=d&&"orientation"in d?fa(d.orientation.type,"landscape"):-90==c.orientation||90==c.orientation;b.V&&(!e&&b.U?b.U&&(b.video.fullscreenExit(),b.U=!1):e&&"playing_manual"==b.getPlayingState()&&b.K&&E(b.o,"viewer").isVisible()&&!b.video.isFullscreen()&&!b.U&&(b.video.fullscreenEnter(),b.U=b.video.isFullscreen()))};if(d&&"orientation"in d){var g=d.orientation;M(g,"change",e.bind(a))}M(c,"orientationchange",
e.bind(a))}}function ib(a,b){if(b.hasDocking&&(a.na||(eb(a.ampdoc),a.na=E(a.ampdoc,"position-observer")),a.na.observe(b.video.element,1,function(a){b.onDockableVideoPositionChanged(a)}),!a.wa)){var c=function(){for(var b=0;b<a.A.length;b++)a.A[b].refreshDockedVideo()};a.l.onResize(c);a.wa=!0}}function kb(a,b){for(var c=0;c<a.A.length;c++)if(a.A[c].video===b)return a.A[c];x().error("video-manager","video is not registered to this video manager");return null}
h.getVideoAnalyticsDetails=function(a){var b;a:{for(b=0;b<this.A.length;b++){var c=this.A[b];if(c.video.element===a){b=c;break a}}x().error("video-manager","video is not registered to this video manager");b=null}return b?b.getAnalyticsDetails():Promise.resolve()};h.getPlayingState=function(a){return kb(this,a).getPlayingState()};h.userInteractedWithAutoPlay=function(a){return kb(this,a).userInteractedWithAutoPlay()};h.canDock=function(a){return!this.X||this.X==a};
h.registerDocked=function(a){this.X=a};h.unregisterDocked=function(){this.X=null;for(var a=0;a<this.A.length;a++)this.A[a].W=!1};
function gb(a,b,c){var d=this;this.ka=a;this.o=a.ampdoc;this.l=I(this.o);this.video=b;this.Ea=c;this.La=null;this.U=this.K=this.O=this.V=!1;this.m=F(this.o.win,"vsync");this.ca=new R;this.ca.onSessionEnd(function(){return T(d,"video-session")});this.R=new R;this.R.onSessionEnd(function(){return T(d,"video-session-visible")});this.da=lb.bind(null,this.o.win,ca(this.o.win).lite);b=b.element;this.ma=this.ua=this.ba=!1;this.I=this.w=null;this.M=!1;this.D=this.j=null;this.G=this.B="inline";this.T=0;this.fa=
null;this.ja=this.Z=this.J=this.P=this.ga=this.W=!1;this.h={mouse:{x:0,y:0},displacement:{x:0,y:0},initial:{x:0,y:0},position:{x:0,y:0},previous:{x:0,y:0},velocity:{x:0,y:0}};this.ha=[];this.hasDocking=b.hasAttribute("dock");this.hasAutoplay=b.hasAttribute("autoplay");var e=b.getAttribute("fullscreen-on-landscape");this.hasFullscreenOnLandscape=""==e||"always"==e;this.C=Ya;Da(b).then(function(){return d.videoLoaded()});M(b,"pause",function(){T(d,"video-pause");d.O=!1;d.ma?d.ma=!1:d.ca.endSession()});
M(b,"playing",function(){return mb(d)});M(b,"muted",function(){return d.M=!0});M(b,"unmuted",function(){return d.M=!1});M(b,"ended",function(){T(d,"video-ended")});this.updateVisibility();this.hasAutoplay&&nb(this);this.hasDocking&&ob(this)}function mb(a){a.O=!0;a.video.preimplementsMediaSessionAPI()||Za(a.o.win,a.C,function(){a.video.play(!1)},function(){a.video.pause()});a.ca.beginSession();a.K&&a.R.beginSession();T(a,"video-play")}h=gb.prototype;
h.videoLoaded=function(){var a=this;this.V=!0;this.w=this.video.element.querySelector("video, iframe");this.m.measure(function(){a.j=a.video.element.getBoundingClientRect()});pb(this);this.updateVisibility();this.K&&qb(this)};
function pb(a){if(!a.video.preimplementsMediaSessionAPI()){a.video.getMetadata()&&(a.C=ea(a.video.getMetadata()));var b=a.o.win.document;if(!a.C.artwork||0==a.C.artwork.length){var c;(c=ab(b))||(c=(c=b.querySelector('meta[property="og:image"]'))?c.getAttribute("content"):void 0);c||(c=(c=b.querySelector('link[rel="shortcut icon"]')||b.querySelector('link[rel="icon"]'))?c.getAttribute("href"):void 0);var d=c;d&&(a.C.artwork=[{src:d}])}!a.C.title&&(b=a.video.element.getAttribute("title")||a.video.element.getAttribute("aria-label")||
a.w.getAttribute("title")||a.w.getAttribute("aria-label")||b.title)&&(a.C.title=b)}}function qb(a){E(a.o,"viewer").isVisible()&&a.da().then(function(b){var c=a.hasAutoplay&&!a.ba;c&&b?a.Ea&&(a.K?(a.R.beginSession(),a.video.play(!0),a.ua=!0):(a.O&&a.R.endSession(),a.video.pause(),a.ma=!0)):a.K?a.R.beginSession():a.O&&a.R.endSession()})}
function nb(a){a.video.isInteractive()&&a.video.hideControls();a.da().then(function(b){!b&&a.video.isInteractive()?a.video.showControls():(a.video.mute(),a.video.isInteractive()&&rb(a))})}
function rb(a){function b(b){a.m.mutate(function(){g.classList.toggle("amp-video-eq-play",b)})}function c(){this.ba=!0;this.video.showControls();this.video.unmute();k.forEach(function(a){a()});qa(g);qa(f)}function d(){K(f,{display:"none"})}function e(){K(f,{display:"block"})}a.video.hideControls();var g=sb(a),f=tb(a);a.m.mutate(function(){a.video.element.appendChild(g);a.video.element.appendChild(f)});var k=[];k.push(M(f,"click",c.bind(a)));k.push(M(g,"click",c.bind(a)));k.push(M(a.video.element,
"pause",b.bind(a,!1)));k.push(M(a.video.element,"playing",b.bind(a,!0)));k.push(M(a.video.element,"ad_start",d.bind(a)));k.push(M(a.video.element,"ad_end",e.bind(a)))}function ob(a){a.m.run({measure:function(){a.j=a.video.element.getBoundingClientRect()},mutate:function(){a.video.element.classList.add("i-amphtml-dockable-video")}})}function U(a,b,c,d){return(d=void 0===d?!1:d)?Ia(a.T,a.j.height,0,b,c):Ia(a.T,0,a.j.height,b,c)}
h.refreshDockedVideo=function(){var a=this;this.m.run({measure:function(){a.j=a.video.element.getBoundingClientRect();ub(a)},mutate:function(){a.G="inline";if(a.fa)a.onDockableVideoPositionChanged(a.fa);vb(a)}})};function ub(a){a.m.measure(function(){a.D=a.w.getBoundingClientRect();a.h.initial.x=a.D.left;a.h.initial.y=a.D.top;a.h.position.x=a.D.left;a.h.position.y=a.D.top;a.h.previous.x=a.D.left;a.h.previous.y=a.D.top;a.h.displacement.x=0;a.h.displacement.y=0})}
function vb(a){a.I&&a.w&&a.m.mutate(function(){function b(a){var b;b=c;b=(a=xa(b.style,a))?b.style[a]:void 0;return b}var c=a.w;K(a.I,{top:b("top"),left:b("left"),bottom:b("bottom"),right:b("right"),transform:b("transform"),"transform-origin":b("transform-origin"),borderRadius:b("borderRadius"),width:b("width"),height:b("height"),position:"fixed","z-index":"17",background:"transparent"})})}
h.onDockableVideoPositionChanged=function(a){var b=this;this.m.run({measure:function(){b.j=b.video.element.getBoundingClientRect();var c="bottom"==a.relativePos,d="top"==a.relativePos,e="inside"==a.relativePos;b.fa=a;a.positionRect||(a.positionRect=c?Fa(b.j.left,b.l.getHeight(),b.j.width,b.j.height):Fa(b.j.left,-b.j.height,b.j.width,b.j.height));var g=a.viewportRect.top,f=a.viewportRect.bottom,k=a.positionRect.top,l=a.positionRect.bottom;b.T=k<=g?l-g:l>=f?f-k:l-k;b.W=b.W||Math.ceil(b.T)>=b.j.height;
g=b.video.element.offsetTop;f=b.l.getScrollHeight()-g-b.video.element.offsetHeight;c&&g<b.l.getHeight()||d&&f<b.l.getHeight()?b.B="inline":b.video.element.offsetHeight>=b.l.getHeight()?b.B="inline":(g=b.o.win.document,"inline"!=b.B||e)?e&&(b.B="inline"):d?b.B=ua(g)?"top_left":"top_right":c&&(b.B=ua(g)?"bottom_left":"bottom_right")},mutate:function(){if(b.V&&b.j&&b.w&&("playing_manual"==b.getPlayingState()||b.w.classList.contains("i-amphtml-dockable-video-minimizing"))){var a="inline"!=b.B&&b.W,d=
"playing_manual"==b.getPlayingState(),e="paused"==b.getPlayingState(),g=b.w.classList.contains("i-amphtml-dockable-video-minimizing");if(a&&(d||e&&g)){if("inline"==b.G&&b.ka.canDock(b)&&(b.video.hideControls(),b.w.classList.add("i-amphtml-dockable-video-minimizing"),K(b.w,{height:b.j.height+"px",width:b.j.width+"px",maxWidth:b.j.width+"px"}),K(b.video.element,{"background-color":"#222"}),b.G="docking",b.ka.registerDocked(b)),"inline"!=b.G){var f=b.l.getWidth(),k=b.l.getHeight(),l=f-.6*b.j.width-20,
n=k-.6*b.j.height-20,p=f=0;switch(b.B){case "top_left":f=p=20;break;case "top_right":p=l;f=20;break;case "bottom_left":f=n;p=20;break;case "bottom_right":f=n,p=l}k=Math.max(0,Math.min(k-b.j.height,b.j.top));p=U(b,b.j.left,p,!0)+"px";f=U(b,k,f,!0)+"px";f=za(p,f);k="scale("+U(b,.6,1)+")";K(b.w,{transform:f+" "+k,transformOrigin:"top left",bottom:"auto",top:"0px",right:"auto",left:"0px"});.6==U(b,.6,1)?b.G="docked":b.G="docking"}}else g&&wb(b);"docked"==b.G?xb(b):yb(b)}}})};
function V(a,b,c,d){a.ha.push(Aa(b,c,d))}
function xb(a){a.ga||a.m.run({measure:function(){ub(a)},mutate:function(){a.I=a.o.win.document.createElement("i-amphtml-dragging-mask");vb(a);a.video.element.appendChild(a.I);V(a,a.I,"mousedown",function(b){b.preventDefault();a.P=!0;a.J=!1;W(a,b,!0)});V(a,a.o.win.document,"mouseup",function(){a.P=!1;a.J=!1;X(a)});V(a,a.o.win.document,"mousemove",function(b){a.J=a.P;a.J&&(b.preventDefault(),a.G="draggable",X(a));W(a,b)});V(a,a.I,"touchstart",function(b){b.preventDefault();a.P=!0;a.J=!1;W(a,b,!0)});
V(a,a.o.win.document,"touchend",function(){a.P=!1;a.J=!1;X(a)});V(a,a.o.win.document,"touchmove",function(b){a.J=a.P;a.J&&(b.preventDefault(),a.G="draggable",X(a));W(a,b)});a.ga=!0}})}
function X(a){a.m.run({measure:function(){a.D=a.w.getBoundingClientRect()},mutate:function(){if(a.V&&a.w&&"inline"!=a.B&&0==a.T&&a.w.classList.contains("i-amphtml-dockable-video-minimizing")&&"draggable"==a.G){var b=a.h;if(a.J){b.previous.x=b.position.x;b.previous.y=b.position.y;b.position.x=b.mouse.x-b.displacement.x;b.position.y=b.mouse.y-b.displacement.y;b.velocity.x=b.position.x-b.previous.x;b.velocity.y=b.position.y-b.previous.y;var c=a.D.width,d=a.D.height,e=b.position.x+c/2,g=b.position.y+
d/2;if(e>a.l.getWidth()||0>e||g>a.l.getHeight()||0>g)a.ja=!0}else if(b.position.x+=b.velocity.x,b.position.y+=b.velocity.y,b.velocity.x*=.55,b.velocity.y*=.55,a.ja){a.video.pause();wb(a);a.ja=!1;return}if(!a.J&&!a.Z&&3>=Math.abs(b.velocity.x)&&3>=Math.abs(b.velocity.y)){var f=a.l.getWidth()-a.D.width-20,k=a.l.getHeight()-a.D.height-20;zb(a);var l=b.position.x,n=b.position.y;switch(a.B){case "bottom_right":l=f;n=k;break;case "top_right":l=f;n=20;break;case "bottom_left":l=20;n=k;break;case "top_left":n=
l=20}if(b.position.x!=l||b.position.y!=n)a.Z=!0,Ab(a,a.I,l,n),Ab(a,a.w,l,n),a.G="docked"}a.Z||(Bb(a,a.I),Bb(a,a.w));a.J||a.m.mutate(function(){X(a)})}}})}function yb(a){a.m.mutate(function(){for(var b=a.ha.pop();b;)b.call(),b=a.ha.pop();a.ga=!1;a.I&&(qa(a.I),a.I=null)})}
function W(a,b,c){c=void 0===c?!1:c;b.x?(a.h.mouse.x=b.x,a.h.mouse.y=b.y):b.touches&&(a.h.mouse.x=b.touches[0].clientX,a.h.mouse.y=b.touches[0].clientY);c&&(a.h.displacement.x=Math.abs(a.h.position.x-a.h.mouse.x),a.h.displacement.y=Math.abs(a.h.position.y-a.h.mouse.y))}function zb(a){var b=a.l.getWidth()/2,c=a.l.getHeight()/2,d=a.D.width,e=a.D.height,g=a.h.position.x+d/2,f=a.h.position.y+e/2;g>=b?f>=c?a.B="bottom_right":f<c&&(a.B="top_right"):g<b&&(f>=c?a.B="bottom_left":f<c&&(a.B="top_left"))}
function wb(a){yb(a);a.video.showControls();a.w.classList.remove("i-amphtml-dockable-video-minimizing");a.w.setAttribute("style","");K(a.video.element,{"background-color":"transparent"});a.G="inline";a.ka.unregisterDocked()}
function sb(a){var b=a.o.win.document,c=b.createElement("i-amphtml-video-eq");c.classList.add("amp-video-eq");for(var d=1;4>=d;d++){var e=b.createElement("div");e.classList.add("amp-video-eq-col");for(var g=1;2>=g;g++){var f=b.createElement("div");f.classList.add("amp-video-eq-"+d+"-"+g);e.appendChild(f)}c.appendChild(e)}var k=F(a.o.win,"platform");k.isIos()&&c.setAttribute("unpausable","");return c}
function Ab(a,b,c,d){Ra(b,Ta(b,{transform:Sa([Wa(Va(Ua(a.h.position.x,c)),Va(Ua(a.h.position.y,d))),Xa()])})).thenAlways(function(){a.h.position.x=c;a.h.position.y=d;a.Z=!1})}function Bb(a,b){a=za(a.h.position.x+"px",a.h.position.y+"px");K(b,{transform:a+" scale(0.6)","transform-origin":"top left",bottom:"auto",top:"0px",right:"auto",left:"0px"})}function tb(a){a=a.o.win.document.createElement("i-amphtml-video-mask");a.classList.add("i-amphtml-fill-content");return a}
h.updateVisibility=function(a){function b(){d.K!=e&&d.V&&qb(d)}function c(){if(1==a)d.K=!0;else{var b=d.video.element.getIntersectionChangeEntry(),c=u(b.intersectionRatio)?100*b.intersectionRatio:0;d.K=75<=c}}var d=this,e=this.K;this.m.run({measure:c,mutate:b})};h.getPlayingState=function(){return this.O?this.O&&this.ua&&!this.ba?"playing_auto":"playing_manual":"paused"};h.userInteractedWithAutoPlay=function(){return this.ba};
h.getAnalyticsDetails=function(){var a=this,b=this.video;return this.da().then(function(c){var d=a.video.element.getLayoutBox(),e=d.width,d=d.height,g=a.hasAutoplay&&c,f=b.getPlayedRanges(),k=f.reduce(function(a,b){return a+b[1]-b[0]},0);return{autoplay:g,currentTime:b.getCurrentTime(),duration:b.getDuration(),height:d,id:b.element.id,muted:a.M,playedTotal:k,playedRangesJson:JSON.stringify(f),state:a.getPlayingState(),width:e}})};var Y=null;
function lb(a,b){if(Y)return Y;if(b)return Y=Promise.resolve(!1);var c=a.document.createElement("video");c.setAttribute("muted","");c.setAttribute("playsinline","");c.setAttribute("webkit-playsinline","");c.muted=!0;c.playsinline=!0;c.webkitPlaysinline=!0;c.setAttribute("height","0");c.setAttribute("width","0");K(c,{position:"fixed",top:"0",width:"0",height:"0",opacity:"0"});try{var d=c.play();d&&d.catch&&d.catch(function(){})}catch(e){}return Y=Promise.resolve(!c.paused)}
function T(a,b){var c,d=a.video,e=c?Promise.resolve(c):a.getAnalyticsDetails();e.then(function(a){d.element.dispatchCustomEvent(b,a)})};var Cb="aria-describedby aria-label aria-labelledby controls crossorigin disableremoteplayback poster controlsList".split(" "),Db=["loop","preload"],Eb=Cb.concat(Db);
function Fb(a){a=AMP.BaseElement.call(this,a)||this;a.c=null;a.M=!1;a.sa=!1;a.C=Ya;a.L=[];a.ta=!!sa(a.element);var b;var c=a.win;if(c.__AMP__EXPERIMENT_TOGGLES)b=c.__AMP__EXPERIMENT_TOGGLES;else{c.__AMP__EXPERIMENT_TOGGLES=Object.create(null);b=c.__AMP__EXPERIMENT_TOGGLES;if(c.AMP_CONFIG)for(var d in c.AMP_CONFIG){var e=c.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(b[d]=Math.random()<e)}if(c.AMP_CONFIG&&Array.isArray(c.AMP_CONFIG["allow-doc-opt-in"])&&0<c.AMP_CONFIG["allow-doc-opt-in"].length&&
(d=c.AMP_CONFIG["allow-doc-opt-in"],e=c.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var e=e.getAttribute("content").split(","),g=0;g<e.length;g++)-1!=d.indexOf(e[g])&&(b[e[g]]=!0);Object.assign(b,va(c));if(c.AMP_CONFIG&&Array.isArray(c.AMP_CONFIG["allow-url-opt-in"])&&0<c.AMP_CONFIG["allow-url-opt-in"].length)for(d=c.AMP_CONFIG["allow-url-opt-in"],c=q(c.location.originalHash||c.location.hash),e=0;e<d.length;e++)g=c["e-"+d[e]],"1"==g&&(b[d[e]]=!0),"0"==g&&(b[d[e]]=!1)}a.Ka=
!b["disable-amp-story-hls"];return a}aa(Fb,AMP.BaseElement);h=Fb.prototype;h.preconnectCallback=function(a){var b=this.element.getAttribute("src");if(!b){var c=this.element.getElementsByTagName("source")[0]||null;c&&(b=c.getAttribute("src"))}var d=b;d&&(C(d,this.element),this.preconnect.url(d,a))};h.prerenderAllowed=function(){return this.sa};h.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a};
h.buildCallback=function(){this.c=this.element.ownerDocument.createElement("video");var a=this.element.getAttribute("poster");!a&&ca().development&&console.error('No "poster" attribute has been provided for amp-video.');var b;a:{b=t(H(this.element,"> source"));b.push(this.element);for(var c=0;c<b.length;c++)if(Z(b[c])){b=!0;break a}b=!1}this.sa=b;this.c.setAttribute("playsinline","");this.c.setAttribute("webkit-playsinline","");this.c.setAttribute("preload","none");this.propagateAttributes(Cb,this.c,
!0);Gb(this);this.applyFillContent(this.c,!0);this.element.appendChild(this.c);var d=this.element.getAttribute("artist");b=this.element.getAttribute("title");var e=this.element.getAttribute("album"),c=this.element.getAttribute("artwork");this.C={title:b||"",artist:d||"",album:e||"",artwork:[{src:c||a||""}]};ma(this.element,"video-manager",fb);E(this.element,"video-manager").register(this,!this.ta)};
h.mutatedAttributesCallback=function(a){if(this.c){a.src&&(C(this.element.getAttribute("src"),this.element),this.propagateAttributes(["src"],this.c));var b=Eb.filter(function(b){return void 0!==a[b]});this.propagateAttributes(b,this.c,!0);a.src&&this.element.dispatchCustomEvent("reloaded");if(a.artwork||a.poster){var c=this.element.getAttribute("artwork"),d=this.element.getAttribute("poster");this.C.artwork=[{src:c||d||""}]}a.album&&(c=this.element.getAttribute("album"),this.C.album=c||"");a.title&&
(c=this.element.getAttribute("title"),this.C.title=c||"");a.artist&&(c=this.element.getAttribute("artist"),this.C.artist=c||"")}};h.viewportCallback=function(a){this.element.dispatchCustomEvent("amp:video:visibility",{visible:a})};
h.layoutCallback=function(){var a=this;this.c=this.c;if(!this.c.play)return this.toggleFallback(!0),Promise.resolve();var b=E(this.getAmpDoc(),"viewer");this.propagateAttributes(Db,this.c,!0);Hb(this);"prerender"==b.getVisibilityState()?(this.element.hasAttribute("preload")||this.c.setAttribute("preload","auto"),b.whenFirstVisible().then(function(){Ib(a)})):Ib(this);return this.loadPromise(this.c).then(function(){a.element.dispatchCustomEvent("load")})};
function Hb(a){var b=t(H(a.element,"> source"));if(a.element.hasAttribute("src")&&Z(a.element)){var c=a.element.getAttribute("src"),d=a.element.getAttribute("type"),e=Jb(a,c,d),g=a.element.getAttribute("amp-orig-src");e.setAttribute("amp-orig-src",g);b.unshift(e)}b.forEach(function(b){Z(b)&&Kb(a,b)&&a.c.appendChild(b)})}
function Ib(a){var b=t(H(a.element,"> source"));a.element.hasAttribute("src")&&!Z(a.element)&&(C(a.element.getAttribute("src"),a.element),a.propagateAttributes(["src"],a.c));b.forEach(function(b){Kb(a,b)?(Z(b),C(b.getAttribute("src"),b),a.c.appendChild(b)):a.element.removeChild(b)});t(a.c.querySelectorAll("[amp-orig-src]")).forEach(function(b){var c=b.getAttribute("amp-orig-src"),d=b.getAttribute("type"),f=Jb(a,c,d),k=a.c,l=f,n=b;n?n.nextSibling?k.insertBefore(l,n.nextSibling):k.appendChild(l):k.insertBefore(l,
k.firstChild)});var c=t(H(a.element,"> track"));c.forEach(function(b){a.c.appendChild(b)})}function Z(a){var b=a.getAttribute("src"),c=a.hasAttribute("amp-orig-src");if(a=c)"string"==typeof b&&(b=B(b)),a=ga.test(b.origin);return a}function Jb(a,b,c){C(b,a.element);a=a.element.ownerDocument.createElement("source");a.setAttribute("src",b);c&&a.setAttribute("type",c);return a}
function Kb(a,b){if(!a.ta||a.Ka)return!0;a=(b.getAttribute("type")||"").toLowerCase();return"application/x-mpegurl"!==a&&"application/vnd.apple.mpegurl"!==a}function Gb(a){var b=a.c;a.L.push(a.forwardEvents(["playing","pause","ended"],b));a.L.push(M(b,"volumechange",function(){a.M!=a.c.muted&&(a.M=a.c.muted,a.element.dispatchCustomEvent(a.M?"muted":"unmuted"))}))}
h.resetOnDomChange=function(){var a;a=this.element;null==G&&(G=ta(a));if(G)a=a.querySelector(":scope > video");else{a.classList.add("i-amphtml-scoped");var b=a.querySelector(".i-amphtml-scoped > video");a.classList.remove("i-amphtml-scoped");a=b}for(this.c=a;this.L.length;)this.L.pop().call();Gb(this)};h.pauseCallback=function(){this.c&&this.c.pause()};h.supportsPlatform=function(){return!!this.c.play};h.isInteractive=function(){return this.element.hasAttribute("controls")};
h.play=function(){var a=this.c.play();a&&a.catch&&a.catch(function(){})};h.pause=function(){this.c.pause()};h.mute=function(){this.c.muted=!0};h.unmute=function(){this.c.muted=!1};h.showControls=function(){this.c.controls=!0};h.hideControls=function(){this.c.controls=!1};
h.fullscreenEnter=function(){var a=this.c,b=a.requestFullscreen||a.requestFullScreen||a.webkitRequestFullscreen||a.webkitRequestFullScreen||a.webkitEnterFullscreen||a.webkitEnterFullScreen||a.msRequestFullscreen||a.msRequestFullScreen||a.mozRequestFullscreen||a.mozRequestFullScreen;b&&b.call(a)};
h.fullscreenExit=function(){var a=this.c,b=a.cancelFullScreen||a.exitFullscreen||a.exitFullScreen||a.webkitExitFullscreen||a.webkitExitFullScreen||a.webkitCancelFullScreen||a.mozCancelFullScreen||a.msExitFullscreen;b?b.call(a):(a.ownerDocument&&(b=a.ownerDocument.cancelFullScreen||a.ownerDocument.exitFullscreen||a.ownerDocument.exitFullScreen||a.ownerDocument.webkitExitFullscreen||a.ownerDocument.webkitExitFullScreen||a.ownerDocument.webkitCancelFullScreen||a.ownerDocument.mozCancelFullScreen||a.ownerDocument.msExitFullscreen),
b&&b.call(a.ownerDocument))};h.isFullscreen=function(){var a;a=this.c;a=a.webkitDisplayingFullscreen?!0:a.ownerDocument&&(a.ownerDocument.fullscreenElement||a.ownerDocument.webkitFullscreenElement||a.ownerDocument.mozFullScreenElement||a.webkitCurrentFullScreenElement)==a?!0:!1;return a};h.getMetadata=function(){return this.C};h.preimplementsMediaSessionAPI=function(){return!1};h.getCurrentTime=function(){return this.c.currentTime};h.getDuration=function(){return this.c.duration};
h.getPlayedRanges=function(){for(var a=this.c.played,b=a.length,c=[],d=0;d<b;d++)c.push([a.start(d),a.end(d)]);return c};(function(a){a.registerElement("amp-video",Fb)})(self.AMP);
})});
//# sourceMappingURL=amp-video-0.1.js.map

